### ISSUE TITLE
大神请教一下如何在基本换肤界面切换皮肤后每个item的图片为不同图片

### ISSUE THREAD

**Issue by Rockwel** [burgessjp/ThemeSkinning#10]

**Comment by burgessjp** [comment]
说具体一点吧

**Comment by Rockwel** [comment]
比如item图片是从list数据中获取的不同图片，切换皮肤后list图片数据更换能否切换成不同的。如下图中的每个item的图片是不一样的，切换皮肤后也要能更换成皮肤中相同的名称的不同图片，左耳可换成别一个图片，失孤换不一样的图片。
![image](https://cloud.githubusercontent.com/assets/2590231/21034083/03818582-bdf0-11e6-931e-aedd096d3c52.png)

**Comment by burgessjp** [comment]
ImageView中展示的是来源于网络的图片，你对这个换肤没实际意义，如果想是现肯定是可以的，不过你的图片必须来源于你的资源，不过不建议这样做。

**Comment by Rockwel** [comment]
实现方案是怎么做的，我这边有个项目需要更换一个主题，图片数据换一下。

**Comment by burgessjp** [comment]
我实在不太懂你的需求，要更换ImageView的图片，你可以去看看之前close的issue
