### ISSUE TITLE
如果项目中是用的style定义的background，有没有好点的解决方案

### ISSUE THREAD

**Issue by lhholylight** [burgessjp/ThemeSkinning#12]

**Comment by burgessjp** [comment]
现在没想到什么好的方案，目前能想到的就是那style中的属性，一个一个取出来，将可以换肤的加入到换肤属性的集合中，后面有时间我会再看看

**Comment by burgessjp** [comment]
问题已解决，最新代码已上传。

**Comment by lhholylight** [comment]
@burgessjp 没看懂style换肤要怎么操作

**Comment by burgessjp** [comment]
style中包含有background或者textColor就可以了，你可以去看看我的demo

**Comment by lhholylight** [comment]
我是在Activity的theme中设置的style，好像是用不了你的那种方式..

**Comment by burgessjp** [comment]
这个库是不支持activity的style的，只是针对View的
