### ISSUE TITLE
请问selector中的颜色能改变吗？

### ISSUE THREAD

**Issue by FeverCombo3** [burgessjp/ThemeSkinning#15]
我试了无法切换颜色。

**Comment by burgessjp** [comment]
可以更改的

**Comment by AndroidJohnsonWang** [comment]
@burgessjp 请问selector更改的方法是怎么样的？怎么我试了无效。

**Comment by burgessjp** [comment]
selector直接设置成background就ok了。

**Comment by erichyx** [comment]
@burgessjp 那textColor属性的selector那怎么实现颜色切换？

**Comment by SeptemberOver** [comment]
@burgessjp  动态添加的TextView的textColor，无法使用selector，请问怎么处理呢？

**Comment by burgessjp** [comment]
动态添加 和 布局文件里面设置本质是一样的。布局文件你那边有问题吗？
