### ISSUE TITLE
设置全屏后状态栏还是会显示颜色

### ISSUE THREAD

**Issue by lhholylight** [burgessjp/ThemeSkinning#17]
使用getWindow().addFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN);设置全屏后，状态栏会显示设置的statusbar颜色，给statusbar设置透明也无效

**Comment by burgessjp** [comment]
你可以关闭状态栏换肤。<code>SkinConfig.setCanChangeStatusColor(false)</code>

**Comment by lhholylight** [comment]
这种写法不是很理想，比如我的app是需要状态栏换肤的，但是可能仅仅只有几个页面需要全屏，这个SkinConfig.setCanChangeStatusColor(false)代码一加后其他页面状态栏就都无法换肤了

**Comment by burgessjp** [comment]
你也可以重写Activity的changeStatusColor方法，不做任何的操作。很多答案都可以从源码中找到答案

**Comment by lhholylight** [comment]
有一个很大的问题，就是我当前有个Activity需要设置状态栏颜色，可是在某个时刻（比如播放视频，或者预留图片时）需要全屏，根本就没办法去实现
