### ISSUE TITLE
对于Fix Issues9解决方案的疑惑

### ISSUE THREAD

**Issue by erichyx** [burgessjp/ThemeSkinning#20]
最新的代码中，在SkinBaseFragment类的onDestroyView()方法里，移除了Fragment相关的View，但是在SkinInflaterFactory类的成员变量mSkinItemMap里只是移除了Fragment本身的View，那些子View并未从 mSkinItemMap里移除，那样的话子View还是不能被释放内存。不知道我的理解是否有误，希望作者能解答一下！

**Comment by burgessjp** [comment]
onDestroyView方法，这里遍历了所有被销毁Fragment中所有的View，最后对每一个View都调用了
SkinInflaterFactory中的removeSkinView方法：
```html
  public void removeSkinView(View view) {
        mSkinItemMap.remove(view);
  }
```
所以是从mSkinItemMap中移除了的。

**Comment by erichyx** [comment]
ok，之前看错了，原来removeView()是递归调用，那就没问题了。
