### ISSUE TITLE
对于Fix Issues9解决方案的疑惑

### ISSUE THREAD

**Issue by erichyx** [burgessjp/ThemeSkinning#21]
最新的代码中，在SkinBaseFragment类的onDestroyView()方法里，移除了Fragment相关的View，但是在SkinInflaterFactory类的成员变量mSkinItemMap里只是移除了Fragment本身的View，那些子View并未从mSkinItemMap里移除，那样的话子View还是不能被释放内存。不知道我的理解是否有误，希望作者能解答一下！

**Comment by l1239155492** [comment]
That means it right.
