### ISSUE TITLE
请问对于一些自定义控件换肤要怎么实现？

### ISSUE THREAD

**Issue by zczhzy** [burgessjp/ThemeSkinning#22]
比如https://github.com/H07000223/FlycoTabLayout 这种，项目里用到了这个做导航菜单，需要更换导航上的图标。
这类自定义控件换肤怎么实现呢？

**Comment by burgessjp** [comment]
这个库子的目的是换肤，也就是对背景和字体颜色做一些改变。其实更改图标不是这个库的目的，但也是可以实现的，关于实现你可以参考一下README里面的换肤属性的扩展
