### ISSUE TITLE
你好 请问如何使用ImageView的src属性

### ISSUE THREAD

**Issue by GoombaCN** [burgessjp/ThemeSkinning#25]
还是说 如果想使用换肤 必须在代码中动态设置setImageDrawable()？

**Comment by burgessjp** [comment]
不太清楚你们为什么会有src切换的要求，src是用来显示ImageView需要展示的图片，按理说这个不应该在换肤的范围内。要做当然也是可以办到的，详细的说明你可以查看 换肤属性的扩展的说明，不过不太建议去做。

**Comment by GoombaCN** [comment]
好的  十分感谢！
至于切换src 比如项目里有一些icon是亮色的 夜间模式的话需要变成暗色 
通常来说这些icon都是用ImageView承载 宽高都是wrap_content 然后使用src属性显示图标

**Comment by burgessjp** [comment]
好的，有时间我在库里加上这个。

**Comment by l1239155492** [comment]
GZIPInputStream
