### ISSUE TITLE
getDrawable方法的改进建议

### ISSUE THREAD

**Issue by erichyx** [burgessjp/ThemeSkinning#26]
SkinManager类的getDrawable方法，目前只能从drawable目录下加载。
在自己扩展属性的时候，有可能需要从其他目录（比如anim）下加载drawable，因此希望能够加一个新的方法，可以自己指定目录，就像这样 getDrawable(String defType, int resId)。

**Comment by burgessjp** [comment]
你所说的从anim下加载drawable是什么意思，不是太理解

**Comment by erichyx** [comment]
@burgessjp 就是在res下有个anim目录，然后我想动态替换anim下的某个xml文件，这时候就需要用“anim”作为defType。

**Comment by burgessjp** [comment]
这个库的目的是换肤，并不是用于去动态切换文件的，你所说的这个需求，并不属于换肤的范围。

**Comment by erichyx** [comment]
@burgessjp 因为xml里面也有drawable属性，所以必须要替换掉整个文件，才能替换里面的drawable，也是换肤的一种应用。比如xml文件里是以下的内容，我要替换android:drawable属性的图片，就只能是替换整个文件了。
<rotate android:drawable="@drawable/icon_largeloading" android:pivotX="50.0%" android:pivotY="50.0%"
  xmlns:android="http://schemas.android.com/apk/res/android" />

**Comment by erichyx** [comment]
@burgessjp xml文件内容
![image](https://cloud.githubusercontent.com/assets/10595445/22632334/5146bed6-ec53-11e6-8c6b-15c8f3b3ec7d.png)

**Comment by burgessjp** [comment]
你的意思是你会这样用 ？
```html
android:drawble="@anim/xxxx"
````
但是我好像没见过这样的用法

**Comment by erichyx** [comment]
@burgessjp 比如那种转圈的进度条就会这样用
![image](https://cloud.githubusercontent.com/assets/10595445/22633024/f7d05b72-ec58-11e6-8b91-ffbe0ae14aae.png)

**Comment by burgessjp** [comment]
大概知道了。

**Comment by burgessjp** [comment]
想了下，这个没必要。你把那个xml文件放到drawble文件夹里就可以了

**Comment by burgessjp** [comment]
想了下，这个没必要，一般背景图都会来自于drawable。你把那个xml文件放到drawable文件夹里就可以了

**Comment by erichyx** [comment]
@burgessjp 视图动画的xml一般都是放在anim文件夹下，这也是官方推荐的做法，按类别进行存放还是有必要的。

**Comment by burgessjp** [comment]
这里你将其当做drawble来用，我认为是完全可以放到drawble文件夹下的

**Comment by erichyx** [comment]
@burgessjp 可以是可以，但是drawable一般是放selector的，希望你这个库能够提供一些灵活性，能够支持从其他目录加载不是更好吗

**Comment by burgessjp** [comment]
目前在SkinManager中已经增加了一个[getTrueResId](https://github.com/burgessjp/ThemeSkinning/blob/master/skinlibrary/src/main/java/solid/ren/skinlibrary/loader/SkinManager.java#L278)方法，也许对你会有用

**Comment by erichyx** [comment]
@burgessjp Thanks, buddy!

**Comment by erichyx** [comment]
@burgessjp 直接返回int感觉还是不行，这样我外面不能直接用的，最好能直接返回Drawable对象。

**Comment by burgessjp** [comment]
那个方法本来就是存在的,你可以仔细看下 [SkinManager](https://github.com/burgessjp/ThemeSkinning/blob/master/skinlibrary/src/main/java/solid/ren/skinlibrary/loader/SkinManager.java)

**Comment by erichyx** [comment]
@burgessjp  原来的getDrawable只有一个参数，不能改变defType，正确的做法是增加一个getDrawable(String defType, int resId)的方法。

**Comment by burgessjp** [comment]
后面版本更新会加上
