### ISSUE TITLE
getDrawable方法的改进建议（二）

### ISSUE THREAD

**Issue by erichyx** [burgessjp/ThemeSkinning#27]
![image](https://cloud.githubusercontent.com/assets/10595445/22632231/7bc4429c-ec52-11e6-9bd0-78d8287e8109.png)
在int trueResId = mResources.getIdentifier(resName, "drawable", skinPackageName);这句里得到了trueResId，这时候应该先判断trueResId是否为0，等于0的话直接返回originDrawable即可。

如果不判断的话，虽然try catch可以捕获到异常，但是不是很好的写法，可以用判断处理的就不要通过抛异常处理。在应用提交到一些自动化测试平台（比如阿里）的时候，会检测应用抛出异常的次数，目前我在应用里集成这个库，自动化测试平台报出调用这个库发生了100多个异常，这样会认为应用的健壮性差。库里getColor方法也一样有这个问题，所以希望能够改进下。

**Comment by burgessjp** [comment]
这个我前段时间想到了，一直没时间修改，后面我一定会去改了。感谢建议
