### ISSUE TITLE
请问如何对?attr/colorPrimaryDark这种类型的引用更换主题

### ISSUE THREAD

**Issue by sususweet** [burgessjp/ThemeSkinning#28]
如题，能否给出相关文档，是继承SkinAttr这个类吗？
另：主页的文档好像不是最新的，还希望作者更新一下哦

**Comment by burgessjp** [comment]
现在是不支持这种的，目前只支持类似于这样的 @color/xxx

**Comment by burgessjp** [comment]
主页文档差不多就是最新的，目前的更新知识在解决bug和细节优化

**Comment by tangyqyq** [comment]
我记得好像ContextCompat没有getAttr这类的方法吧，请问可以用什么方法来实现题中的效果
