### ISSUE TITLE
一个关于drawable的问题

### ISSUE THREAD

**Issue by GoombaCN** [burgessjp/ThemeSkinning#29]
此Issue主要目的是讨论

小弟不才 因为想写一个换icon的demo 发现按步骤配置之后不生效 于是排查了一下问题所在
最终定位在SkinManager类的312行 
`int trueResId = mResources.getIdentifier(resName, "drawable", skinPackageName);`

原因是第二个参数写死为drawable 而我想换的资源文件在mipmap中
所以此时 trueResId必然为0 
期望替换的图片也不会被替换

虽说是约定优于配置 但还是感觉对于一些场景不太灵活
比如 有个项目已经做完了 版本迭代时提出要添加换肤功能 
而此时项目中大部分图片都放置在mipmap中 
如果把mipmap中所有图片搬到drawable 显然工作量不小 而且容易出错

个人建议是 getDrawable() 函数中
 if (trueResId == 0) {
            trueDrawable = originDrawable;
        }
修改成
  if(trueResId==0) {
        trueResId = mResources.getIdentifier(resName, "mipmap", skinPackageName);
        if (trueResId == 0) {
            trueDrawable = originDrawable;
        }
        else{
            //do something
        }
    }

未通读所有原代码 不能保证其正确与合理性
仅供查验与参考 有误望指出

**Comment by burgessjp** [comment]
可行的，我后面加上。
