### ISSUE TITLE
命名空间会报错找不到

### ISSUE THREAD

**Issue by snowjade** [burgessjp/ThemeSkinning#31]
![image](https://cloud.githubusercontent.com/assets/11959369/23012647/33a749e2-f462-11e6-8537-e61bd9fb5682.png)

当自身是安卓原生控件，然后父控件也都是原生控件时。skin:enable="true"  会报错。

**Comment by burgessjp** [comment]
这个是lint警告，对代码的执行没影响，加上 tools:ignore="MissingPrefix"就不会有了

**Comment by snowjade** [comment]
谢谢，是个解决方案。
