### ISSUE TITLE
运行不了

### ISSUE THREAD

**Issue by liukepeng** [burgessjp/ThemeSkinning#4]
Error:A problem occurred configuring project ':app'.
> Could not find support-v4.jar (com.android.support:support-v4:24.0.0).
  Searched in the following locations:
      https://jcenter.bintray.com/com/android/support/support-v4/24.0.0/support-v4-24.0.0.jar

**Comment by burgessjp** [comment]
v4包没下载

**Comment by tianshaokai** [comment]
我的sdk 里是有这个包的 ，也报这个问题

**Comment by burgessjp** [comment]
这个不是代码的问题，必需你自己取检测你的编译环境。

**Comment by tianshaokai** [comment]
已经可以运行了修改了gradle 版本，看了半天代码没看懂换肤的具体原理，作者是否可以讲解一下呢
