### ISSUE TITLE
RadioButton设置的background无法动态更换皮肤

### ISSUE THREAD

**Issue by XuanJiAndroid** [burgessjp/ThemeSkinning#43]
当前使用版本:1.4.6

在background中设置selecter,其select中引用的资源名和插件中的资源名完全一致，通过 skin:enable="true" 无法动态更换，
随后我使用dynamicAddView函数也无法更换

**Comment by burgessjp** [comment]
设置 background 是肯定支持的，但是对于RadioButton的选中样式需要设置button而不是background ，目前库还没支持button，后面有时间会加上
