### ISSUE TITLE
android widget换肤如何实现？

### ISSUE THREAD

**Issue by jicunxin** [burgessjp/ThemeSkinning#45]
widget使用widgetprovider创建，并不能通过activity和fragment进行换肤，请问有遇到过这种情况么，如何处理？

**Comment by burgessjp** [comment]
不是inflalator加载的布局你可以试试动态添加

**Comment by jicunxin** [comment]
那这样是不是得继承或者实现接口，然后自己处理

**Comment by burgessjp** [comment]
如果是在Activity或者Fragment中创建的这个Widget，可以直接调用 `dynamicAddSkinEnableView` 这个方法去添加需要换肤的 `View`

**Comment by jicunxin** [comment]
我说的这个widget是桌面小插件，应该不行的，得按照你activity里的思路完全实现一下才可以的

**Comment by burgessjp** [comment]
@jicunxin 本质都是一样的，应该是可行。自己实现当然也是可以的
