### ISSUE TITLE
不能切肤问题

### ISSUE THREAD

**Issue by dongdengke** [burgessjp/ThemeSkinning#48]
之前切肤时可以的，今天启动APP后，突然间不行了。用的时1.3.1版本

**Comment by burgessjp** [comment]
你可以试试切换到最新的版本

**Comment by dongdengke** [comment]
我试了最新最新的版本，和1.3.1一样。5.0以后不不可以，5.0以上的是可以的。

**Comment by burgessjp** [comment]
那你只能把调试信息打开，看看log检查原因了。

**Comment by burgessjp** [comment]
这个问题我先关闭了，如果还有问题，你可以重新打开。
