### ISSUE TITLE
为啥不能通过Activity的主题来改变来换肤

### ISSUE THREAD

**Issue by 1479HuangDa** [burgessjp/ThemeSkinning#49]

**Comment by burgessjp** [comment]
当然可以。Android自带的日夜间模式且换就是用的这种方式。换肤还是有很多种实现方式，看项目需求你可以选择用哪一种去实现。

**Comment by 1479HuangDa** [comment]
可是换肤过后恢复 状态栏颜色不对啊 你在这里就是直接去取@color/colorPrimaryDark的颜色 不合理把 要是不同的activity 我要让状态栏显示不同的颜色 怎么办

**Comment by burgessjp** [comment]
这里我确实还没有提供对某个Activity是否改变状态栏颜色的方法。你可以在你的不需要自动换状态栏颜色的 `Activity` 中复写下  `changeStatusColor()`  这个方法，里面不需要有任何的代码，可以解决你的问题。后面的更新中我会提供一个api。

**Comment by 1479HuangDa** [comment]
我试试看看
