### ISSUE TITLE
solid.ren.skinlibrary.loader.TextViewRepository的问题

### ISSUE THREAD

**Issue by 1479HuangDa** [burgessjp/ThemeSkinning#50]
在solid.ren.skinlibrary.loader.TextViewRepository类中由于你用了个静态的mTextViews 产生了严重的内存泄漏

**Comment by burgessjp** [comment]
贴一下你使用的版本号，以及具体的泄漏信息。

**Comment by 1479HuangDa** [comment]
![wxvr mmbg3ffdt 8c 9epcd](https://user-images.githubusercontent.com/18064688/28813325-6f0b3f3e-76cb-11e7-99ac-840505c74657.png)
![device-2017-08-01-150620](https://user-images.githubusercontent.com/18064688/28813337-7d607af4-76cb-11e7-8328-6645b31dec60.png)

**Comment by burgessjp** [comment]
昨天我更新了，你可以试试最新版本。
