### ISSUE TITLE
能不能不继承activity。。

### ISSUE THREAD

**Issue by xiaokun19931126** [burgessjp/ThemeSkinning#52]
..

**Comment by burgessjp** [comment]
可以，但是你要将  `SkinBaseActivity` 中的逻辑移植到你的 `Activity` 中

**Comment by xiaokun19931126** [comment]
谢谢你，明白了

_Sent from my Xiaomi Redmi Note 3 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
