### ISSUE TITLE
动态换肤功能

### ISSUE THREAD

**Issue by masite** [burgessjp/ThemeSkinning#54]
SkinManager.getInstance().restoreDefaultTheme():  重置默认皮肤后
退出APP再次打开，动态添加的view就没有图片了。  

动态添加的view用的是  dynamicAddView（imageview, "background",R.drable.**）

请问这种情况怎么解决啊

**Comment by masite** [comment]
没办法回到换肤之前的图片吗？也就是本地的图片。 试着这样写 
       if (SkinConfig.isDefaultSkin(MainActivity.this)) {
            ImageView imageView = (ImageView) view;
            imageView.setImageResource(attrValueResId);
        } else {
            dynamicAddView(view, attrName, attrValueResId);
        }

结果却是同时显示了两套。

**Comment by burgessjp** [comment]
我这边测试没有问题的，你可以看最新的Demo，动态添加的View  本身也应该设置一张图片。
