### ISSUE TITLE
RadioButton字体颜色选择器换不了

### ISSUE THREAD

**Issue by tangsw7** [burgessjp/ThemeSkinning#55]
自定义Attr了,radiobutton的图片可以换,但是文字用颜色选择器改变不了,还是默认皮肤颜色

**Comment by burgessjp** [comment]
看看你的自定义Attr部分代码

**Comment by tangsw7** [comment]
public class RadioButtonTextAttr extends SkinAttr {
    @Override
    protected void applySkin(View view) {
        if (view instanceof RadioButton) {
            if (isDrawable()) {
                RadioButton radioButton = (RadioButton) view;
                radioButton.setTextColor(SkinResourcesUtils.getColorStateList(attrValueRefId));
            }
        }
    }
}

**Comment by tangsw7** [comment]
好像是所有字体颜色选择器都不行,只换字体颜色是可以换的

**Comment by burgessjp** [comment]
不好意思，最近有点忙，没能及时回复，有时间了我才能去看看这个问题，其实你也可以先看看源码呃呃实现。

_Sent from my Xiaomi MI 6 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by burgessjp** [comment]
我在demo中加了一个颜色选择器的例子，完全是可以的，不知道你是怎么使用的，你可以看最新的demo。
