### ISSUE TITLE
我有一个自定义的TextView,然后这个View很多布局里面都有,但是我又不想每个布局里面去设置enable = true,我能通过代码来设置允许更换背景或者文字颜色吗?

### ISSUE THREAD

**Issue by Coder-StarLing** [burgessjp/ThemeSkinning#6]
如果可以的话能否贴一下代码?方便的话可以加一下我的QQ吗?840103844 以便有不懂的地方能问一下

**Comment by burgessjp** [comment]
目前没什么好的解决方案，后面再想想有什么好的办法没

**Comment by Monster-L** [comment]
可以在SkinInflaterFactory判断是否需要换肤时兼容你的自定义view，最简单的是加个判断，你也可以搞个白名单的数组
if (isSkinEnable||TextUtils.equals(name,你想全部换肤的view名字)) {
...
}

**Comment by burgessjp** [comment]
是个办法，多谢建议，我再考虑下。

**Comment by burgessjp** [comment]
目前添加了一个开启全局皮肤的方法，调用了这个方法，就不需要去添加 <code>"enable" = true</code>
