### ISSUE TITLE
ImageView 动态换肤

### ISSUE THREAD

**Issue by xxxxx-xx** [burgessjp/ThemeSkinning#62]
为什么我这个ImageVIew动态换肤，无效？我调试了，好像是无法获取到皮肤skin中mipmap中的图片资源？

**Comment by burgessjp** [comment]
你可以看看我给的demo，有这样的例子

_Sent from my Xiaomi MI 6 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by xxxxx-xx** [comment]
我可以了。我卸载了重新安装一下就可以了。
