### ISSUE TITLE
库兼容

### ISSUE THREAD

**Issue by NeverMore906065383** [burgessjp/ThemeSkinning#63]
'com.android.support:appcompat-v7:26.1.0'   和其他多个开源框架不兼容v7:25.1.0'

**Comment by burgessjp** [comment]
exclude group: 'com.android.support'

**Comment by NeverMore906065383** [comment]
我是下载到本地引入，并且添加了autolayout的部分代码。使用的v7:25.1.0，修改SkinInflaterFactory中部分代码来解决的。3Q
