### ISSUE TITLE
旧版本更换新图片无法更新

### ISSUE THREAD

**Issue by MrxMo** [burgessjp/ThemeSkinning#65]
1、旧版本更换新的图片无法跟随主题，清除数据就正常了，[图片名称加了版本也不行](https://github.com/burgessjp/ThemeSkinning/issues/56)
2、第一次集成时，很奇怪，有一款皮肤的部分地方没生效，其他皮肤正常

**Comment by burgessjp** [comment]
1.[issue 56](https://github.com/burgessjp/ThemeSkinning/issues/56) 是给你的皮肤库加版本名
2.你可以再看看我最新的demo
