### ISSUE TITLE
对于Style 配置的属性，解析到的entryName 值不对

### ISSUE THREAD

**Issue by msdx** [burgessjp/ThemeSkinning#67]
在Activity Theme 配置了textColor，
在TextView 中使用到了一个Style，Style里指定了另一个 TextColor。获取到的值不是这个TextView的Style里所指定的TextColor，而是Theme里的textColor。

**Comment by msdx** [comment]
在 SkinInflaterFactory 中解析style是解析 `/` 之后的名称，但实际上attrValue 取到的值也可能是类似 `@2131558740` 或 `?16842872` 这样的值，导致取到的是 theme 的 style 而不是 view 里声明的 style

**Comment by burgessjp** [comment]
嗯。这段时间有点忙，没太多时间去维护这个库，不过这里我的获取方式是根据styleId去获取的，按理说不应该有问题的。但是也感觉你的pull request，有时间了我会去处理下。

**Comment by msdx** [comment]
确实是有问题的。实际上你是想通过style的名称去取到其对应的styleId，再根据这styleId去取到对应的style。但是实际上在xml中你用`/`分割取出来的并不一定是styleId，在xml中的style值可能是一个@1234567或者是一个?1234567之类的值，这会使styleId取不到，从而`context.getTheme().obtainStyledAttributes(styleID, skinAttrs);`拿到的是在context的theme中的TypedArray，因此从这个TypedArray中读到的值也就是在theme中定义的TextColor值而不是布局里的style里的值了。

**Comment by burgessjp** [comment]
在xml中style都是 @style/xxx 这样赋值的，?attr/xxx 这样赋值才可能出现你说的 ?1234567 的情况吧

_Sent from my Xiaomi MI 6 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
