### ISSUE TITLE
研究了一天问几个问题

### ISSUE THREAD

**Issue by tianshaokai** [burgessjp/ThemeSkinning#7]
![image](https://cloud.githubusercontent.com/assets/6706496/20748945/3aecb2c4-b72b-11e6-8512-d9cf1142f866.png)

1.我圈起来的这部分是做什么替换的呢？
2. 我想给imageview 换图片该怎么弄呢？
3. 可不可以换布局文件呢，把整个布局文件都替换掉
4. 布局文件里的skin:enable="true" 属性是怎么加载的呢，我只要写了这个属性就可以换颜色了，这个属性在xml 里不认识 studio 一直报红色，如何解决这个问题呢

希望作者看看我的问题

**Comment by tianshaokai** [comment]
![image](https://cloud.githubusercontent.com/assets/6706496/20749295/b25c7bf4-b72c-11e6-81e1-39924ef34217.png)
![image](https://cloud.githubusercontent.com/assets/6706496/20749309/be74a4fc-b72c-11e6-9dd0-f4fcba3b278d.png)

这两个类看着不理解 希望作者可以讲解一下，上边那个图里的方法主要是用来做什么的呢？？

**Comment by burgessjp** [comment]
1.你看SkinManager的源码就知道了
2.给imageView设置background就可以了
3.这个不是这个库的目的，并且这个需求也没得必要
4.这个是lint警告，对待吗没影响，加上<code> tools:ignore="MissingPrefix"</code>就不会有了
