### ISSUE TITLE
如何网络获取皮肤切换

### ISSUE THREAD

**Issue by AllenYi** [burgessjp/ThemeSkinning#78]
您好，下载的demo源码里面没有看到网络获取皮肤的功能，我使用v2.0.0 beta7版本也没有发现有网络获取皮肤更换的方法，请问这一块该怎么做？求指教。

**Comment by burgessjp** [comment]
这个很简单啊，你先从网络把文件下载到本地，然后调用换肤方法就行了。

_Sent from my Xiaomi MI 6 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by AllenYi** [comment]
好的，谢谢，大神。
