### ISSUE TITLE
动态创建一个ImageView,如何允许更换图片?

### ISSUE THREAD

**Issue by Rockwel** [burgessjp/ThemeSkinning#8]
我是按照下面方式创建的，但是没有更换。
 ImageView imb = new ImageView(getContext());
 imb.setImageDrawable(getResources().getDrawable(R.drawable.pi12));
 ViewGroup.MarginLayoutParams paramsimg = new ViewGroup.MarginLayoutParams(ViewGroup.LayoutParams.WRAP_CONTENT, ViewGroup.LayoutParams.WRAP_CONTENT);
 imb.setLayoutParams(paramsimg);
 dynamicAddView(imb, "background", R.drawable.pi12);

**Comment by burgessjp** [comment]
ImageView 不支持这样做的，因为他没有setBackgroundDrawable这个方法。你可以自定义换肤属性，Readme文档里有说明的，示例项目中也有一个Demo。

**Comment by Rockwel** [comment]
多谢大神指导，问题解决啦！看来还是没有理解透彻这个项目源码。
